services:
  app:
    labels:
      - traefik.http.routers.app.entrypoints=websecure
      - traefik.http.routers.app.tls=true
      - traefik.http.routers.app.tls.certresolver=le
    volumes:
      - /srv/servelink/traefik:/data/traefik
      - /srv/servelink/upload:/app/upload
      - /srv/servelink/access.json:/app/settings/access.json

  worker-arq:
    volumes:
      - /srv/servelink/traefik:/data/traefik

  pgsql:
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - default

  traefik:
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.endpoint=tcp://docker-proxy:2375
      - --providers.docker.watch=true
      - --providers.file.directory=/etc/traefik/dynamic_conf
      - --providers.file.watch=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --certificatesresolvers.le.acme.email=${LE_EMAIL}
      - --certificatesresolvers.le.acme.storage=/etc/traefik/dynamic_conf/acme.json
      - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /srv/servelink/traefik:/etc/traefik/dynamic_conf