"""empty message

Revision ID: 061c3f846ed9
Revises: 
Create Date: 2025-01-27 20:40:08.821754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '061c3f846ed9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('configuration', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_configuration_created_at'), ['created_at'], unique=False)

    op.create_table('deployment',
    sa.Column('id', sa.String(length=22), nullable=False),
    sa.Column('project_id', sa.String(length=22), nullable=False),
    sa.Column('repo', sa.JSON(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('env_vars_id', sa.Integer(), nullable=False),
    sa.Column('commit_sha', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('queued', 'in_progress', 'completed', name='deployment_status'), nullable=False),
    sa.Column('conclusion', sa.Enum('succeeded', 'failed', 'canceled', 'skipped', name='deployment_conclusion'), nullable=True),
    sa.Column('trigger', sa.Enum('webhook', 'user', 'api', name='deployment_trigger'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('concluded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['configuration.id'], ),
    sa.ForeignKeyConstraint(['env_vars_id'], ['environment_variables.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deployment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deployment_commit_sha'), ['commit_sha'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployment_concluded_at'), ['concluded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployment_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployment_project_id'), ['project_id'], unique=False)

    op.create_table('environment_variables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('environment_variables', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_environment_variables_created_at'), ['created_at'], unique=False)

    op.create_table('github_installation',
    sa.Column('installation_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=2048), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('installation_id')
    )
    op.create_table('project',
    sa.Column('id', sa.String(length=22), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('repo_id', sa.BigInteger(), nullable=False),
    sa.Column('repo_full_name', sa.String(length=255), nullable=False),
    sa.Column('repo_branch', sa.String(length=255), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=True),
    sa.Column('env_vars_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('active_deployment_id', sa.String(length=22), nullable=True),
    sa.ForeignKeyConstraint(['active_deployment_id'], ['deployment.id'], ),
    sa.ForeignKeyConstraint(['config_id'], ['configuration.id'], ),
    sa.ForeignKeyConstraint(['env_vars_id'], ['environment_variables.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_repo_branch'), ['repo_branch'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_repo_full_name'), ['repo_full_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_repo_id'), ['repo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_user_id'), ['user_id'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('github_token', sa.String(length=2048), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_github_id'), ['github_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_name'))
        batch_op.drop_index(batch_op.f('ix_user_github_id'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_user_id'))
        batch_op.drop_index(batch_op.f('ix_project_updated_at'))
        batch_op.drop_index(batch_op.f('ix_project_repo_id'))
        batch_op.drop_index(batch_op.f('ix_project_repo_full_name'))
        batch_op.drop_index(batch_op.f('ix_project_repo_branch'))
        batch_op.drop_index(batch_op.f('ix_project_name'))
        batch_op.drop_index(batch_op.f('ix_project_created_at'))

    op.drop_table('project')
    op.drop_table('github_installation')
    with op.batch_alter_table('environment_variables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_environment_variables_created_at'))

    op.drop_table('environment_variables')
    with op.batch_alter_table('deployment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deployment_project_id'))
        batch_op.drop_index(batch_op.f('ix_deployment_created_at'))
        batch_op.drop_index(batch_op.f('ix_deployment_concluded_at'))
        batch_op.drop_index(batch_op.f('ix_deployment_commit_sha'))

    op.drop_table('deployment')
    with op.batch_alter_table('configuration', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_configuration_created_at'))

    op.drop_table('configuration')
    # ### end Alembic commands ###
