"""empty message

Revision ID: 0fd6372d4ab1
Revises: b94804f6925b
Create Date: 2025-02-18 11:12:53.861028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fd6372d4ab1'
down_revision = 'b94804f6925b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subdomain', sa.String(length=63), nullable=False),
    sa.Column('deployment_id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.Enum('branch', 'environment', name='alias_type'), nullable=True),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployment.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subdomain')
    )
    with op.batch_alter_table('alias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alias_deployment_id'), ['deployment_id'], unique=False)

    with op.batch_alter_table('deployment', schema=None) as batch_op:
        batch_op.drop_column('slug')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deployment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.VARCHAR(length=63), nullable=True))

    with op.batch_alter_table('alias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alias_deployment_id'))

    op.drop_table('alias')
    # ### end Alembic commands ###
