"""empty message

Revision ID: a9696c6650ea
Revises: 061c3f846ed9
Create Date: 2025-02-03 12:27:11.718555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9696c6650ea'
down_revision = '061c3f846ed9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deployment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('container_id', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deployment', schema=None) as batch_op:
        batch_op.drop_column('container_id')

    # ### end Alembic commands ###
