"""empty message

Revision ID: aeb7bf5b2c90
Revises: b2e1c8f3c8ab
Create Date: 2025-04-03 14:33:56.578228

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'aeb7bf5b2c90'
down_revision = 'b2e1c8f3c8ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deployment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('commit_sha', sa.String(length=40), nullable=False))
        batch_op.add_column(sa.Column('commit_meta', sa.JSON(), nullable=False))
        batch_op.create_index(batch_op.f('ix_deployment_branch'), ['branch'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployment_commit_sha'), ['commit_sha'], unique=False)
        batch_op.drop_column('commit')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deployment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commit', sqlite.JSON(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_deployment_commit_sha'))
        batch_op.drop_index(batch_op.f('ix_deployment_branch'))
        batch_op.drop_column('commit_meta')
        batch_op.drop_column('commit_sha')
        batch_op.drop_column('branch')

    # ### end Alembic commands ###
