"""empty message

Revision ID: d5e6f45932f2
Revises: 6a52e1589d52
Create Date: 2025-05-27 09:03:19.423574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5e6f45932f2'
down_revision = '6a52e1589d52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alias', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_alias_subdomain'), ['subdomain'])

    with op.batch_alter_table('deployment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('container_status', sa.Enum('running', 'stopped', 'removed', name='deployment_container_status'), nullable=True))

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_project_slug'), ['slug'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_project_slug'), type_='unique')

    with op.batch_alter_table('deployment', schema=None) as batch_op:
        batch_op.drop_column('container_status')

    with op.batch_alter_table('alias', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_alias_subdomain'), type_='unique')

    # ### end Alembic commands ###
