"""empty message

Revision ID: d8ccee896894
Revises: 
Create Date: 2025-03-06 19:32:21.901459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8ccee896894'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_installation',
    sa.Column('installation_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=2048), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('active', 'deleted', 'suspended', name='github_installation_status'), nullable=False),
    sa.PrimaryKeyConstraint('installation_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('github_token', sa.String(length=2048), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_github_id'), ['github_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('project',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('repo_id', sa.BigInteger(), nullable=False),
    sa.Column('repo_full_name', sa.String(length=255), nullable=False),
    sa.Column('repo_status', sa.Enum('active', 'deleted', 'removed', 'transferred', name='project_github_status'), nullable=False),
    sa.Column('github_installation_id', sa.Integer(), nullable=False),
    sa.Column('environments', sa.JSON(), nullable=False),
    sa.Column('env_vars', sa.Text(), nullable=False),
    sa.Column('slug', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'paused', 'deleted', name='project_status'), nullable=False),
    sa.Column('mapping', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['github_installation_id'], ['github_installation.installation_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_github_installation_id'), ['github_installation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_repo_full_name'), ['repo_full_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_repo_id'), ['repo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_user_id'), ['user_id'], unique=False)

    op.create_table('deployment',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('repo', sa.JSON(), nullable=False),
    sa.Column('container_id', sa.String(length=64), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('env_vars', sa.Text(), nullable=False),
    sa.Column('commit', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'in_progress', 'completed', name='deployment_status'), nullable=False),
    sa.Column('conclusion', sa.Enum('succeeded', 'failed', 'canceled', 'skipped', name='deployment_conclusion'), nullable=True),
    sa.Column('trigger', sa.Enum('webhook', 'user', 'api', name='deployment_trigger'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('concluded_at', sa.DateTime(), nullable=True),
    sa.Column('build_logs', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deployment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deployment_concluded_at'), ['concluded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployment_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployment_project_id'), ['project_id'], unique=False)

    op.create_table('alias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subdomain', sa.String(length=63), nullable=False),
    sa.Column('deployment_id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.Enum('branch', 'environment', name='alias_type'), nullable=True),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployment.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subdomain')
    )
    with op.batch_alter_table('alias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alias_deployment_id'), ['deployment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alias_deployment_id'))

    op.drop_table('alias')
    with op.batch_alter_table('deployment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deployment_project_id'))
        batch_op.drop_index(batch_op.f('ix_deployment_created_at'))
        batch_op.drop_index(batch_op.f('ix_deployment_concluded_at'))

    op.drop_table('deployment')
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_user_id'))
        batch_op.drop_index(batch_op.f('ix_project_updated_at'))
        batch_op.drop_index(batch_op.f('ix_project_repo_id'))
        batch_op.drop_index(batch_op.f('ix_project_repo_full_name'))
        batch_op.drop_index(batch_op.f('ix_project_name'))
        batch_op.drop_index(batch_op.f('ix_project_github_installation_id'))
        batch_op.drop_index(batch_op.f('ix_project_created_at'))

    op.drop_table('project')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_name'))
        batch_op.drop_index(batch_op.f('ix_user_github_id'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('github_installation')
    # ### end Alembic commands ###
